# Generated by Django 5.2.6 on 2025-09-16 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='cpf',
        ),
    ]
