# Generated by Django 5.2.6 on 2025-09-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_colaborador_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(default=True),
        ),
    ]
