# Generated by Django 5.2.6 on 2025-09-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_equipamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(default='novo', max_length=100),
        ),
    ]
