# Generated by Django 5.2.6 on 2025-09-29 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='status',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='colaborador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.colaborador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(auto_now_add=True, default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='equipamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.equipamento'),
            preserve_default=False,
        ),
    ]
