# Generated by Django 5.2.6 on 2025-09-30 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_emprestimo_nome_remove_emprestimo_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 30, 22, 29, 0, 824153, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
